[tools]
bun        = "1.2.14"
cargo-binstall = "1.12.0"
cosign = "2.5.0"
go         = "1.24.3"
node       = "22.14.0"
python     = "3.12.9"
rust       = "1.86.0"
uv         = "0.6.17"

[settings]
env                    = [".env"]
experimental           = true
idiomatic_version_file = false
# task_output            = "quiet"
trusted_config_paths   = ["~/code"]

[settings.npm]
bun = true
[settings.pipx]
uvx = true

[env]
NODE_NO_WARNINGS    = 1
NPM_CONFIG_AUDIT    = "false"
NPM_CONFIG_FUND     = "false"
NPM_CONFIG_LOGLEVEL = "error"
