[tools]
bun            = "1.2.14"
cargo-binstall = "1.12.0"
cosign         = "2.5.0"
go             = "1.24.3"
node           = "22.14.0"
python         = "3.12.10"
rust           = "1.86.0"
slsa-verifier  = "2.7.0"
uv             = "0.6.17"

# checkov    = "3.2.433"
pre-commit = "4.2.0"
shellcheck = "0.10.0"
terraform  = "1.6.6"
yamllint   = "1.37.1"

# "npm:markdownlint-cli2" = "0.18.1"
# "npm:release-please"    = "16.18.0"
# "npm:renovate"          = "40.32.2"
# "pipx:ansible-core"     = { version = "2.18.6", pipx_args = "--preinstall jmespath==1.0.1 --preinstall kubernetes==32.0.1" }
# "pipx:cookiecutter"     = "2.6.0"
# "pipx:flux-local"       = "7.5.0"
# "pipx:poetry"           = "2.1.3"

[settings]
env                    = [".env"]
experimental           = true
idiomatic_version_file = false
# task_output            = "quiet"
trusted_config_paths   = ["~/code"]

[settings.npm]
bun = true
[settings.pipx]
uvx = true

