[tools]
bun        = "1.1.45"
go         = "1.23.6"
node       = "22.12.0"
python     = "3.12.9"
rust       = "1.84.1"
shellcheck = "0.10.0"
terraform  = "1.9.8"
uv         = "0.5.31"
yamllint   = "1.35.1"

"npm:@bitwarden/cli"    = "2025.1.3"
"npm:markdownlint-cli2" = "0.17.2"
"npm:release-please"    = "16.18.0"
"npm:renovate"          = "39.186.0"
"pipx:ansible-core"     = { version = "2.18.1", pipx_args = "--preinstall jmespath==1.0.1 --preinstall kubernetes==31.0.0" }
"pipx:cookiecutter"     = "2.6.0"
"pipx:flux-local"       = "6.1.1"
"pipx:poetry"           = "2.1.1"
pre-commit              = "4.1.0"

[settings]
env                    = [".env"]
experimental           = true
idiomatic_version_file = true
task_output            = "quiet"
trusted_config_paths   = ["~/code"]

[settings.npm]
bun = true
[settings.pipx]
uvx = true
